version: '3' 
services: 
    testman-backend: 
        build: ./backend 
        image: testman2:latest
        ports: 
            - "8080:8080"
        # volumes:
        #     - /home/ubuntu/images/profile:/static/image/profile
        #     - /home/ubuntu/images/diary:/static/image/diary